name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ThinkPad
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: docker compose up -d --build