name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ThinkPad
    runs-on: self-hosted

    env:
      APP_NAME: ${{ variables.APP_NAME}}
      ENVIRONMENT: ${{ variables.ENVIRONMENT}}
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/pruebaTecnica
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_ALGORITHM: ${{ variables.JWT_ALGORITHM}}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${{ variables.JWT_ACCESS_TOKEN_EXPIRE_MINUTES}}
      SMTP_HOST: ${{ variables.SMTP_HOST}}
      SMTP_PORT: ${{ variables.SMTP_PORT}}
      SMTP_USER: ${{ secrets.SMTP_USER}}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD}}
      SMTP_FROM: ${{ secrets.SMTP_FROM}}
      SMTP_SECURE: ${{ variables.SMTP_SECURE}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: docker compose build backend frontend migrations

      - name: Start database
        run: docker compose up -d db

      - name: Run migrations
        run: docker compose run --rm migrations

      - name: Start application
        run: docker compose up -d backend frontend

      - name: Smoke test backend
        run: curl --fail http://localhost:8000/health