name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t prueba-tecnica-backend ./backend

      - name: Build frontend image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_URL=http://thinkpad.local:8000 \
            -t prueba-tecnica-frontend ./frontend